### ISSUE TITLE
Avoid `__init__.py` in thonnycontrib

### ISSUE THREAD

**Issue by aivarannamaa** [epfl-mobots/tdmclient-ty#2]
thonnycontrib is meant to be a [namespace package](https://peps.python.org/pep-0420/), which means it shouldn't contain `__init__.py`. 

In simpler cases it wouldn't hurt, but in more complex deployment scenarios it could hide plugins at other locations.

**Comment by ypiguet-epfl** [comment]
Thanks a lot, @aivarannamaa ! Fixed in [85d54e9](https://github.com/epfl-mobots/tdmclient-ty/commit/85d54e97aa49106fdc95b4d1f070b6b06732ed52)
