### ISSUE TITLE
Small problem with installation instructions 

### ISSUE THREAD

**Issue by aivarannamaa** [epfl-mobots/tdmclient-ty#3]
Installing a Thonny plug-in via Shell only works if Thonny is configured to use its front-end interpreter also for the back-end.

**Comment by ypiguet-epfl** [comment]
Thanks, @aivarannamaa ! Fixed in [01019e9](https://github.com/epfl-mobots/tdmclient-ty/commit/01019e979428042edddf384c9fb96c0596161d64).
